name: Sync to GitHub Pages

on:
  push:
    branches:
      - 'dreamfyre-*'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    environment:
         name: github-pages
  
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Find latest feature branch with HTML files
        run: |
          LATEST_BRANCH=$(git for-each-ref --sort=-committerdate --format='%(refname:short)' refs/heads/dreamfyre-* | while read branch; do
            if git ls-tree -r --name-only "$branch" | grep -q '\.html$'; then
              echo "$branch"
              break
            fi
          done)
          echo "LATEST_BRANCH=$LATEST_BRANCH" >> $GITHUB_ENV

      - name: Checkout latest branch content
        run: |
          git fetch origin $LATEST_BRANCH
          git checkout $LATEST_BRANCH -- .

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
